///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InterOfferDataModel {
/*
{
  "id": 1001,
  "minute": 1000,
  "day": 30,
  "tk": 796,
  "net": "25 GB",
  "cashback": 80,
  "bonus": ""
}
*/

  int? id;
  int? minute;
  int? day;
  int? tk;
  String? net;
  int? cashback;
  String? bonus;

  InterOfferDataModel({
    this.id,
    this.minute,
    this.day,
    this.tk,
    this.net,
    this.cashback,
    this.bonus,
  });
  InterOfferDataModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    minute = json["minute"]?.toInt();
    day = json["day"]?.toInt();
    tk = json["tk"]?.toInt();
    net = json["net"]?.toString();
    cashback = json["cashback"]?.toInt();
    bonus = json["bonus"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["minute"] = minute;
    data["day"] = day;
    data["tk"] = tk;
    data["net"] = net;
    data["cashback"] = cashback;
    data["bonus"] = bonus;
    return data;
  }
}
